zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka:0.9.0.0
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
    KAFKA_CREATE_TOPICS: "test.topic:4:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
pykafka-shell:
  build: .
  dockerfile: Dockerfile-pykafka
  environment:
    KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
  links:
    - kafka
    - zookeeper
pykafka-producer:
  build: .
  dockerfile: Dockerfile-pykafka-producer
  environment:
    KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
  links:
    - kafka
    - zookeeper
pykafka-consumer:
  build: .
  dockerfile: Dockerfile-pykafka-consumer
  environment:
    KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
  links:
    - kafka
    - zookeeper
